version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cineplanet
    ports:
      - "3306:3306"

  premieres:
    build: ./premieres-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  candystore:
    build: ./candystore-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  complete:
    build: ./complete-service
    ports:
      - "8083:8083"

  frontend:
    build: ./frontend/cineplanet-web
    ports:
      - "3000:3000"
    depends_on:
      - premieres
      - candystore
      - complete
